#!/usr/local/bin/ruby
require "fileutils"
class String
  def to_camel
    self.strip.gsub(/(-|\/|\s|<|_)(.)/) {|e| $2.upcase}
  end
end
current_folder = `pwd`.chomp
if current_folder.end_with? "ResourcesManager"
  current_folder = "#{current_folder}/scripts"
end
Current_folder = current_folder
Parent_folder = File.dirname(Current_folder)
Resources_Bundle_folder = "#{Parent_folder}/Resources.bundle"
Resource_folder = "#{Resources_Bundle_folder}/images"
Output_folder = "#{Parent_folder}/Sources/generated/"
Output_file = "#{Output_folder}/Image.swift"
FileUtils.mkdir_p Output_folder
FileUtils.rm_rf Output_file

def generated
  class_name = "ImageResource"
  preface = "// This file is auto-generated by image_parser.rb, do not modify! \n"
  preface += "// Generated at " + Time.now.strftime("%d/%m/%Y %H:%M") + "\n\n"
  total_line = preface
  total_line += "extension #{class_name} {\n" +

  pngs = Dir["#{Resource_folder}/*.png"]
  pngs.each do |png|
    base_name = File.basename(png).gsub(/.png/,'')
    var_name = base_name.to_camel
    file_name = base_name.gsub(/.png/,'')
    total_line += "\tpublic static var #{var_name}: UIImage { return pngImage(named: \"#{file_name}\") }\n"
  end

  pdfs = Dir["#{Resource_folder}/*.pdf"]
  pdfs.each do |png|
    base_name = File.basename(png).gsub(/.pdf/,'')
    var_name = base_name.to_camel
    file_name = base_name
    total_line += "\tpublic static var #{var_name}: UIImage { return image(named: \"#{file_name}\") }\n"
  end

  total_line += "}"
  open(Output_file, 'w') { |f|
    f.puts total_line
  }
end
generated
